#!/usr/bin/env bash
#script to output Best school 10 times using while loop with a Hi on the 9th line
COUNT=9
while((COUNT>=0));do
	echo "Best School"
	if [ "$COUNT" -eq 1 ] ;then
		echo "Hi"
	fi
((COUNT--))
done;
